#!/usr/bin/env bash
benchmark=$1
nodepath=${2:-node}
shift 2;
cwd=${PWD}

trap 'cd "$cwd"' EXIT

if [ "$benchmark" = "doxbee" ]; then
    cd "$cwd"
    npm install
    echo "Doxbee sequential"
    $nodepath performance.js --n 10000 --t 1 ./doxbee-sequential/*.js --harmony "$@"
    exit 0
elif [ "$benchmark" = "parallel" ]; then
    cd "$cwd"
    npm install
    echo "Madeup parallel"
    $nodepath performance.js --n 10000 --t 1 --p 25 ./madeup-parallel/*.js --harmony "$@"
    exit 0
else
    echo "Invalid benchmark name $benchmark"
    exit -1
fi
